<div id="threequal-col">
<div id="one">
<h1>LSST Brochure</h1>
<h5>The Widest, Fastest, Deepest, Eye of the New Digital Age</h5>
<p>The Large Synoptic Survey Telescope is a proposed wide-field
telescope facility with a qualitatively new capability to
open a fresh perspective on the universe.<p/> 
<h6>THE WORLD'S LARGEST DIGITAL CAMERA</h6>
<p>In order to take full advantage of its ten square-degree field of view,
the LSST will use a three billion pixel camera with a circular array of
189 innovative detector modules that stretches across 63 centimeters.
A novel monolithic 8.4-meter primary mirror and 5.2-meter tertiary
mirror combination will be kept in tight alignment with its 3.4-meter
wide secondary mirror.<br /><br />
The overall system will obtain sequential images of the entire observable sky, which can then be combined to provide a digital image of unprecedented depth and area coverage, or subtracted from each other to highlight celestial sources that change in brightness, position, or both. A distinguishing feature of the LSST approach is that science from the nearby solar system to "big picture" cosmology can be carried out in parallel, using a common set of images and the same  observation cadence to address a wide diversity of science goals.<p/><br />
<img src= "/files/img/brochtele.png">
</div>


<div id="two">
<p class="caption" align="center">400kb Preview:<p/>
<p align="center"><a href="/files/docs/brochure.jpg">English</a> I <a href="/files/docs/brochure_spanish.jpg">Espa&ntilde;ol</a></p>
<img src="/files/img/mov.png" ><p/></div><div/>


<div id="three">
<p class="caption" align="center">8.7mb Download:<p/>
<p align="center"><a href="/files/docs/brochure.pdf">English</a> I <a href="/files/docs/brochure_spanish.pdf">Espa&ntilde;ol</a></p>
<h5>La mas amplia, rapida y prof- unda mirada de la nueva era digital</h5>
<p>El Gran Telescopio de Inspecci&oacute;n Sin&oacute;ptica (Large Synoptic Survey
Telescope, LSST) es un telescopio de campo amplio, propuesto
con una capacidad cualitativamente nueva de proporcionar
una perspectiva renovada del universo.
<h6>LA CAMARA DIGITAL MAS GRANDE DEL MUNDO</h6>
<p>A fin de obtener la mejor ventaja posible de su campo visual de 10
grados cuadrados, el telescopio LSST usar&aacute; una c&aacute;mara de tres mil
megapixeles en un arreglo circular de 189 m&oacute;dulos detectores de
&uacute;ltima generaci&oacute;n, que se extiende por 63 cent&iacute;metros de ancho. La
original combinaci&oacute;n de un espejo monol&iacute;tico consistente de un
primario de 8.4 metros y un espejo terciario de 5.0 metros, se
mantendr&aacute; en estrecha alineaci&oacute;n con su espejo secundario de 3.4 metros. 
<br /><br />
El sistema obtendr&aacute; im&aacute;genes secuenciales de todo el cielo observable,las que se podr&aacute;n combinar para proporcionar una imagen digital de profundidad y cobertura de &aacute;rea sin precedente, o se podr&aacute;n sustraer im&aacute;genes para resaltar fuentes celestes cuya brillantez o posici&oacute;n es variable, o ambas. Una caracter&iacute;stica que distingue la metodolog&iacute;a del LSST es que la ciencia del cercano sistema solar y la de la amplia perspectiva cosmol&oacute;gica pueden desarrollarse en paralelo, usando el mismo conjunto de im&aacute;genes y la misma cadencia de observaci&oacute;n para realizar una amplia variedad de objetivos cient&iacute;ficos.<p/>
</div>

</div>
